# ==============================================================================
# TRANSCRIPTOME vs. PROTEOME COMPARISON ACROSS MULTIPLE TISSUES
# Integrates RNA-seq log2FC with three proteomics metrics per tissue:
#   (1) Soluble protein fraction
#   (2) Insoluble protein fraction
#   (3) Insoluble/Soluble ratio (protein aggregation index)
#
# Outputs:
#   - 15 individual PDFs (5 tissues x 3 comparisons)
#   - 1 combined facet PDF (all tissues, annotated with R2 and gene labels)
#   - 1 combined facet PDF (all tissues, clean)
#   - 15 matched gene CSVs (one per tissue x comparison)
#   - 1 R2 summary CSV
#
# Expected folder structure:
#   project_root/
#   |-- transcriptome_proteome_comparison.R   <- this script
#   |-- data/
#   |   |-- rnaseq_data.csv                   <- RNA-seq data
#   |   +-- proteomics/                       <- proteomics CSVs folder
#   |       |-- Tissue1_processed.csv
#   |       |-- Tissue2_processed.csv
#   |       |-- Tissue3_processed.csv
#   |       |-- Tissue4_processed.csv
#   |       +-- Tissue5_processed.csv
#   +-- output/                               <- all plots and CSVs saved here
#
# Proteomics CSVs are generated by the companion processing script.
#
# INPUT DATA FORMAT:
#   RNA-seq CSV columns (per tissue):
#     Log2.Ratio...{ID}.CondA.vs.{ID}.CondB.   <- log2 fold change
#     P.value..{ID}.CondA.vs.{ID}.CondB.        <- p-value
#     sig..{ID}.CondA.vs.{ID}.CondB.            <- significance flag (0/1)
#
#   Proteomics CSV columns (required):
#     GN                  <- gene name (used for matching to RNA-seq Symbol)
#     Protein.Accession   <- protein accession
#     Description         <- protein description
#     Log2FC_soluble      <- log2FC soluble fraction (CondA/CondB)
#     p_value_soluble
#     Log2FC_insoluble    <- log2FC insoluble fraction (CondA/CondB)
#     p_value_insoluble
#     Log2FC_ratio        <- log2FC insoluble/soluble ratio (CondA/CondB)
#     p_value_ratio
# ==============================================================================

# ==================== LIBRARIES ====================
suppressPackageStartupMessages({
  library(tidyverse)
  library(ggrepel)
  library(readr)
  library(scales)
})

# ==============================================================================
# USER CONFIG -- edit these settings before running
# ==============================================================================

# Path to RNA-seq data file (relative to project root)
RNASEQ_FILE    <- "data/rnaseq_data.csv"

# Path to folder containing proteomics processed CSV files
PROTEOMICS_DIR <- "data/proteomics"

# Path to output folder (will be created if it does not exist)
OUTPUT_DIR     <- "output"

# ------------------------------------------------------------------------------
# Tissue mapping:
# Each entry maps a short ID (matching RNA-seq column names) to:
#   file  -> proteomics CSV filename prefix (file = "{prefix}_processed.csv")
#   label -> display name used in plot titles and legends
# ------------------------------------------------------------------------------
tissue_map <- list(
  T1 = list(file = "Tissue1", label = "Tissue 1"),
  T2 = list(file = "Tissue2", label = "Tissue 2"),
  T3 = list(file = "Tissue3", label = "Tissue 3"),
  T4 = list(file = "Tissue4", label = "Tissue 4"),
  T5 = list(file = "Tissue5", label = "Tissue 5")
)

# ------------------------------------------------------------------------------
# Tissue colors: one color per tissue label defined above
# ------------------------------------------------------------------------------
tissue_colors <- c(
  "Tissue 1" = "darkgreen",
  "Tissue 2" = "purple4",
  "Tissue 3" = "blue4",
  "Tissue 4" = "darkred",
  "Tissue 5" = "darkgoldenrod"
)

# ------------------------------------------------------------------------------
# RNA-seq column name pattern:
# Script expects columns named as:
#   Log2.Ratio...{ID}.CondA.vs.{ID}.CondB.
#   P.value..{ID}.CondA.vs.{ID}.CondB.
#   sig..{ID}.CondA.vs.{ID}.CondB.
# where {ID} matches the keys in tissue_map above (T1, T2, ...).
# Edit COND_A and COND_B to match your actual condition labels.
# ------------------------------------------------------------------------------
COND_A <- "CondA"   # e.g. treatment group
COND_B <- "CondB"   # e.g. control group

# ==============================================================================

# Create output directory if needed
if (!dir.exists(OUTPUT_DIR)) dir.create(OUTPUT_DIR, recursive = TRUE)

# --- Point color scheme for significance categories ---
sig_colors <- c(
  "Neither"          = "grey80",
  "RNA-seq only"     = "#2166AC",  # Blue
  "Proteomics only"  = "#D6604D",  # Orange-red
  "Both"             = "#762A83"   # Purple
)

sig_alphas <- c(
  "Neither"          = 0.25,
  "RNA-seq only"     = 0.55,
  "Proteomics only"  = 0.55,
  "Both"             = 0.85
)

sig_sizes <- c(
  "Neither"          = 0.8,
  "RNA-seq only"     = 1.2,
  "Proteomics only"  = 1.2,
  "Both"             = 2.0
)

# --- Comparison definitions ---
comparisons <- list(
  soluble = list(
    prot_fc  = "Log2FC_soluble",
    prot_p   = "p_value_soluble",
    y_label  = paste0("Log2FC Soluble protein (", COND_A, "/", COND_B, ")"),
    title_kw = "Soluble protein"
  ),
  insoluble = list(
    prot_fc  = "Log2FC_insoluble",
    prot_p   = "p_value_insoluble",
    y_label  = paste0("Log2FC Insoluble protein (", COND_A, "/", COND_B, ")"),
    title_kw = "Insoluble protein"
  ),
  ratio = list(
    prot_fc  = "Log2FC_ratio",
    prot_p   = "p_value_ratio",
    y_label  = paste0("Log2FC Insoluble/Soluble ratio (", COND_A, "/", COND_B, ")"),
    title_kw = "Insolubility ratio"
  )
)

# ==================== LOAD DATA ====================

cat("Loading RNA-seq data...\n")
rnaseq_raw <- read.csv(RNASEQ_FILE)
cat("  Loaded", nrow(rnaseq_raw), "genes\n\n")

# ==================== CORE PLOT FUNCTION ====================

make_comparison_plot <- function(merged, comp, tissue_label, tissue_color) {
  
  # ---- R2 on all matched genes ----
  fit    <- lm(prot_fc ~ rna_fc, data = merged)
  r2_all <- round(summary(fit)$r.squared, 3)
  n_all  <- formatC(nrow(merged), format = "d", big.mark = ",")
  n_both <- sum(merged$sig_group == "Both")
  
  # ---- Top 10 "Both" genes to label (ranked by combined significance) ----
  label_df <- merged %>%
    filter(sig_group == "Both") %>%
    mutate(combined_sig = (-log10(rna_p  + 1e-300)) +
             (-log10(prot_p + 1e-300))) %>%
    arrange(desc(combined_sig)) %>%
    slice_head(n = 10)
  
  merged <- merged %>%
    mutate(label = ifelse(GN %in% label_df$GN, GN, NA_character_))
  
  # ---- Category ordering so purple is drawn on top ----
  merged <- merged %>%
    mutate(sig_group = factor(sig_group,
                              levels = c("Neither", "RNA-seq only",
                                         "Proteomics only", "Both")))
  
  # ---- Axis limits with 5% padding ----
  x_range <- range(merged$rna_fc,  na.rm = TRUE)
  y_range <- range(merged$prot_fc, na.rm = TRUE)
  x_lims  <- x_range + diff(x_range) * c(-0.05, 0.05)
  y_lims  <- y_range + diff(y_range) * c(-0.05, 0.05)
  
  # ---- Build plot ----
  p <- ggplot(merged %>% arrange(sig_group),
              aes(x = rna_fc, y = prot_fc)) +
    geom_hline(yintercept = 0, linetype = "dashed",
               color = "grey60", linewidth = 0.35) +
    geom_vline(xintercept = 0, linetype = "dashed",
               color = "grey60", linewidth = 0.35) +
    geom_point(aes(color = sig_group,
                   alpha = sig_group,
                   size  = sig_group)) +
    scale_color_manual(values = sig_colors, name = "Significance") +
    scale_alpha_manual(values = sig_alphas, name = "Significance") +
    scale_size_manual( values = sig_sizes,  name = "Significance") +
    geom_text_repel(
      aes(label = label),
      color         = "#762A83",
      size          = 3,
      fontface      = "bold",
      max.overlaps  = Inf,
      box.padding   = 0.4,
      point.padding = 0.2,
      segment.color = "grey50",
      segment.size  = 0.3,
      na.rm         = TRUE
    ) +
    scale_x_continuous(labels = label_number(accuracy = 0.1),
                       limits = x_lims) +
    scale_y_continuous(labels = label_number(accuracy = 0.1),
                       limits = y_lims) +
    labs(
      title    = paste0(tissue_label, ": mRNA vs. ",
                        comp$title_kw,
                        " (", COND_A, " vs. ", COND_B, ")"),
      subtitle = paste0("Blue = RNA-seq only  |  Orange-red = Proteomics only  ",
                        "|  Purple = Both significant"),
      x        = paste0("Log2FC mRNA (", COND_A, "/", COND_B, ")"),
      y        = comp$y_label,
      caption  = paste0(
        "Significance thresholds: RNA-seq sig == 1  |  Proteomics p <= 0.05\n",
        "Top 10 purple genes labeled by combined significance (-log10 p RNA-seq + proteomics)\n",
        "Log2FC values represent ", COND_A, "/", COND_B,
        " (positive = increased in ", COND_A, ")\n",
        "R2 = ", r2_all,
        " (all matched genes, n = ", n_all, ")",
        "  |  Both significant: n = ", n_both
      )
    ) +
    theme_minimal(base_size = 12) +
    theme(
      plot.title       = element_text(size = 14, face = "bold"),
      plot.subtitle    = element_text(size = 10, color = "grey40"),
      plot.caption     = element_text(size = 9,  color = "grey30", hjust = 0),
      axis.title       = element_text(size = 12, face = "bold"),
      axis.text        = element_text(size = 11),
      legend.title     = element_text(size = 11, face = "bold"),
      legend.text      = element_text(size = 10),
      legend.position  = "right",
      panel.grid.minor = element_blank()
    )
  
  return(p)
}

# ==================== MAIN LOOP ====================

# Storage for combined facet data
facet_data_list <- list()

for (tiss_id in names(tissue_map)) {
  
  tinfo        <- tissue_map[[tiss_id]]
  tissue_label <- tinfo$label
  tissue_file  <- tinfo$file
  tissue_color <- tissue_colors[[tissue_label]]
  
  cat("========================================\n")
  cat("Processing:", tissue_label, "\n")
  cat("========================================\n")
  
  # ---- Load proteomics ----
  prot_file <- file.path(PROTEOMICS_DIR,
                         paste0(tissue_file, "_processed.csv"))
  
  if (!file.exists(prot_file)) {
    cat("  WARNING: Proteomics file not found:", prot_file, "\n\n")
    next
  }
  
  prot_data <- read.csv(prot_file) %>%
    group_by(GN) %>%
    slice_min(order_by = p_value_ratio, n = 1, with_ties = FALSE) %>%
    ungroup() %>%
    filter(!is.na(GN), GN != "", GN != "NA") %>%
    filter(!grepl("CON_|^co$", GN, ignore.case = TRUE))
  
  cat("  Proteomics genes:", nrow(prot_data), "\n")
  
  # ---- Extract RNA-seq columns for this tissue ----
  # Column name pattern (as read by read.csv, spaces converted to dots):
  #   Log2.Ratio...{ID}.{COND_A}.vs.{ID}.{COND_B}.
  #   P.value..{ID}.{COND_A}.vs.{ID}.{COND_B}.
  #   sig..{ID}.{COND_A}.vs.{ID}.{COND_B}.
  rna_fc_col  <- paste0("Log2.Ratio...", tiss_id, ".", COND_A,
                        ".vs.", tiss_id, ".", COND_B, ".")
  rna_p_col   <- paste0("P.value..",     tiss_id, ".", COND_A,
                        ".vs.", tiss_id, ".", COND_B, ".")
  rna_sig_col <- paste0("sig..",         tiss_id, ".", COND_A,
                        ".vs.", tiss_id, ".", COND_B, ".")
  
  missing_cols <- setdiff(c(rna_fc_col, rna_p_col, rna_sig_col),
                          names(rnaseq_raw))
  if (length(missing_cols) > 0) {
    cat("  WARNING: Missing RNA-seq columns:",
        paste(missing_cols, collapse = ", "), "\n\n")
    next
  }
  
  rna_data <- rnaseq_raw %>%
    select(Symbol,
           rna_fc  = all_of(rna_fc_col),
           rna_sig = all_of(rna_sig_col),
           rna_p   = all_of(rna_p_col)) %>%
    filter(!is.na(Symbol), Symbol != "") %>%
    mutate(rna_fc  = as.numeric(rna_fc),
           rna_sig = as.integer(rna_sig),
           rna_p   = as.numeric(rna_p))
  
  cat("  RNA-seq genes:", nrow(rna_data), "\n")
  
  # ---- Loop over three comparisons ----
  for (comp_name in names(comparisons)) {
    
    comp <- comparisons[[comp_name]]
    cat("  Comparison:", comp_name, "...\n")
    
    # ---- Merge by gene name (RNA-seq Symbol <-> proteomics GN) ----
    merged <- inner_join(
      rna_data,
      prot_data %>%
        select(GN,
               prot_fc = all_of(comp$prot_fc),
               prot_p  = all_of(comp$prot_p)),
      by = c("Symbol" = "GN")
    ) %>%
      rename(GN = Symbol) %>%
      filter(!is.na(rna_fc), !is.na(prot_fc),
             !is.na(rna_p),  !is.na(prot_p)) %>%
      mutate(
        sig_rna   = rna_sig == 1,
        sig_prot  = prot_p  <= 0.05,
        sig_group = case_when(
          sig_rna  & sig_prot  ~ "Both",
          sig_rna  & !sig_prot ~ "RNA-seq only",
          !sig_rna & sig_prot  ~ "Proteomics only",
          TRUE                 ~ "Neither"
        ),
        Tissue     = tissue_label,
        Comparison = comp_name
      )
    
    n_matched <- nrow(merged)
    cat("    Matched genes:", n_matched, "\n")
    cat("    Both significant:", sum(merged$sig_group == "Both"), "\n")
    
    if (n_matched < 5) {
      cat("    WARNING: Too few matched genes, skipping.\n")
      next
    }
    
    # ---- Store for combined facet plot ----
    facet_data_list[[paste(tiss_id, comp_name, sep = "_")]] <- merged
    
    # ---- Export detailed matched gene table ----
    prot_full <- prot_data %>%
      select(
        GN,
        Protein_Accession  = Protein.Accession,
        Description,
        Log2FC_soluble,   p_value_soluble,
        Log2FC_insoluble, p_value_insoluble,
        Log2FC_ratio,     p_value_ratio
      )
    
    export_df <- inner_join(
      rnaseq_raw %>%
        select(
          GN          = Symbol,
          mRNA_Log2FC = all_of(rna_fc_col),
          mRNA_pvalue = all_of(rna_p_col),
          mRNA_sig    = all_of(rna_sig_col)
        ),
      prot_full,
      by = "GN"
    ) %>%
      filter(GN %in% merged$GN) %>%
      mutate(
        Tissue     = tissue_label,
        Comparison = comp_name,
        sig_group  = case_when(
          mRNA_sig == 1 & !!sym(paste0("p_value_", comp_name)) <= 0.05 ~ "Both",
          mRNA_sig == 1 & !!sym(paste0("p_value_", comp_name)) >  0.05 ~ "RNA-seq only",
          mRNA_sig != 1 & !!sym(paste0("p_value_", comp_name)) <= 0.05 ~ "Proteomics only",
          TRUE ~ "Neither"
        )
      ) %>%
      select(
        Tissue, Comparison, GN,
        Protein_Accession, Description,
        mRNA_Log2FC, mRNA_pvalue, mRNA_sig,
        Log2FC_soluble,   p_value_soluble,
        Log2FC_insoluble, p_value_insoluble,
        Log2FC_ratio,     p_value_ratio,
        sig_group
      ) %>%
      arrange(sig_group, GN)
    
    export_file <- paste0("matched_genes_",
                          gsub(" ", "_", tissue_label),
                          "_", comp_name, ".csv")
    write.csv(export_df, file.path(OUTPUT_DIR, export_file),
              row.names = FALSE)
    cat("    Exported:", export_file,
        "(", nrow(export_df), "genes )\n")
    
    # ---- Save individual plot ----
    plot_file <- file.path(OUTPUT_DIR,
                           paste0("transcriptome_vs_", comp_name, "_",
                                  gsub(" ", "_", tissue_label), ".pdf"))
    p <- make_comparison_plot(merged, comp, tissue_label, tissue_color)
    ggsave(plot_file, plot = p, width = 10, height = 8, dpi = 600)
    cat("    Saved:", plot_file, "\n")
  }
  
  cat("\n")
}

# ==================== COMBINED FACET PLOT ====================

cat("========================================\n")
cat("Creating combined facet plots...\n")
cat("========================================\n")

if (length(facet_data_list) > 0) {
  
  all_facet_data <- bind_rows(facet_data_list) %>%
    mutate(
      Tissue     = factor(Tissue, levels = names(tissue_colors)),
      Comparison = factor(Comparison,
                          levels = c("soluble", "insoluble", "ratio"),
                          labels = c("Soluble protein",
                                     "Insoluble protein",
                                     "Insolubility ratio"))
    )
  
  # ---- Per-panel R2 labels ----
  r2_labels <- all_facet_data %>%
    group_by(Tissue, Comparison) %>%
    summarise(
      r2     = round(summary(lm(prot_fc ~ rna_fc))$r.squared, 3),
      n      = n(),
      n_both = sum(sig_group == "Both"),
      x_pos  = quantile(rna_fc,  0.98, na.rm = TRUE),
      y_pos  = quantile(prot_fc, 0.98, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    mutate(label = paste0("R2 = ", r2,
                          "\nn = ", formatC(n, format = "d", big.mark = ","),
                          "\nBoth = ", n_both))
  
  # ---- Top-10 purple labels per facet ----
  label_data <- all_facet_data %>%
    filter(sig_group == "Both") %>%
    mutate(combined_sig = (-log10(rna_p  + 1e-300)) +
             (-log10(prot_p + 1e-300))) %>%
    group_by(Tissue, Comparison) %>%
    arrange(desc(combined_sig)) %>%
    slice_head(n = 10) %>%
    ungroup()
  
  # ---- Shared theme for both combined plots ----
  combined_theme <- theme_minimal(base_size = 10) +
    theme(
      plot.title       = element_text(size = 13, face = "bold"),
      plot.subtitle    = element_text(size = 8,  color = "grey40"),
      plot.caption     = element_text(size = 8,  color = "grey30", hjust = 0),
      strip.text.x     = element_text(size = 10, face = "bold"),
      strip.text.y     = element_text(size = 9,  face = "bold", angle = 0),
      strip.placement  = "outside",
      axis.title.x     = element_text(size = 10, face = "bold"),
      axis.text        = element_text(size = 8),
      legend.position  = "bottom",
      legend.title     = element_text(size = 9,  face = "bold"),
      legend.text      = element_text(size = 8),
      panel.grid.minor = element_blank(),
      panel.spacing    = unit(0.8, "lines")
    )
  
  # ---- Annotated version (R2 + gene labels) ----
  p_combined <- ggplot(all_facet_data %>% arrange(sig_group),
                       aes(x = rna_fc, y = prot_fc)) +
    facet_grid(Comparison ~ Tissue, scales = "free", switch = "y") +
    geom_hline(yintercept = 0, linetype = "dashed",
               color = "grey60", linewidth = 0.3) +
    geom_vline(xintercept = 0, linetype = "dashed",
               color = "grey60", linewidth = 0.3) +
    geom_point(aes(color = sig_group,
                   alpha = sig_group,
                   size  = sig_group)) +
    scale_color_manual(values = sig_colors, name = "Significance") +
    scale_alpha_manual(values = sig_alphas, name = "Significance") +
    scale_size_manual( values = sig_sizes,  name = "Significance") +
    geom_text(data        = r2_labels,
              aes(x = x_pos, y = y_pos, label = label),
              inherit.aes = FALSE,
              hjust = 1, vjust = 1,
              size = 2.2, color = "black") +
    geom_text_repel(
      data          = label_data,
      aes(label     = GN),
      color         = "#762A83",
      size          = 1.8,
      fontface      = "bold",
      max.overlaps  = 12,
      box.padding   = 0.3,
      point.padding = 0.1,
      segment.color = "grey50",
      segment.size  = 0.25,
      na.rm         = TRUE
    ) +
    labs(
      title    = paste0("Transcriptome vs. Proteome: ",
                        COND_A, " vs. ", COND_B, " across five tissues"),
      subtitle = paste0("Blue = RNA-seq only  |  Orange-red = Proteomics only  ",
                        "|  Purple = Both significant\n",
                        "Top 10 purple genes labeled per panel"),
      x        = paste0("Log2FC mRNA (", COND_A, "/", COND_B, ")"),
      y        = NULL,
      caption  = paste0(
        "Significance thresholds: RNA-seq sig == 1  |  Proteomics p <= 0.05\n",
        "Log2FC values represent ", COND_A, "/", COND_B,
        " (positive = increased in ", COND_A, ")\n",
        "R2 shown per panel (all matched genes)  |  Both = significant in both datasets"
      )
    ) +
    combined_theme
  
  ggsave(file.path(OUTPUT_DIR, "transcriptome_vs_proteome_all_tissues.pdf"),
         plot = p_combined, width = 22, height = 14, dpi = 600)
  cat("Saved: transcriptome_vs_proteome_all_tissues.pdf\n")
  
  # ---- Clean version (no labels, no R2) ----
  p_combined_clean <- ggplot(all_facet_data %>% arrange(sig_group),
                             aes(x = rna_fc, y = prot_fc)) +
    facet_grid(Comparison ~ Tissue, scales = "free", switch = "y") +
    geom_hline(yintercept = 0, linetype = "dashed",
               color = "grey60", linewidth = 0.3) +
    geom_vline(xintercept = 0, linetype = "dashed",
               color = "grey60", linewidth = 0.3) +
    geom_point(aes(color = sig_group,
                   alpha = sig_group,
                   size  = sig_group)) +
    scale_color_manual(values = sig_colors, name = "Significance") +
    scale_alpha_manual(values = sig_alphas, name = "Significance") +
    scale_size_manual( values = sig_sizes,  name = "Significance") +
    labs(
      title    = paste0("Transcriptome vs. Proteome: ",
                        COND_A, " vs. ", COND_B, " across five tissues"),
      subtitle = paste0("Blue = RNA-seq only  |  Orange-red = Proteomics only  ",
                        "|  Purple = Both significant"),
      x        = paste0("Log2FC mRNA (", COND_A, "/", COND_B, ")"),
      y        = NULL,
      caption  = paste0(
        "Significance thresholds: RNA-seq sig == 1  |  Proteomics p <= 0.05\n",
        "Log2FC values represent ", COND_A, "/", COND_B,
        " (positive = increased in ", COND_A, ")"
      )
    ) +
    combined_theme
  
  ggsave(file.path(OUTPUT_DIR, "transcriptome_vs_proteome_all_tissues_clean.pdf"),
         plot = p_combined_clean, width = 22, height = 14, dpi = 600)
  cat("Saved: transcriptome_vs_proteome_all_tissues_clean.pdf\n")
  
} else {
  cat("WARNING: No data available for combined facet plots.\n")
}

# ==================== R2 SUMMARY TABLE ====================

cat("\n========================================\n")
cat("Saving R2 summary table...\n")
cat("========================================\n")

if (length(facet_data_list) > 0) {
  
  r2_summary <- bind_rows(facet_data_list) %>%
    group_by(Tissue, Comparison) %>%
    summarise(
      n_matched          = n(),
      n_both_sig         = sum(sig_group == "Both"),
      n_rnaseq_only      = sum(sig_group == "RNA-seq only"),
      n_proteomics_only  = sum(sig_group == "Proteomics only"),
      n_neither          = sum(sig_group == "Neither"),
      R2_all_matched     = round(summary(lm(prot_fc ~ rna_fc))$r.squared, 4),
      .groups = "drop"
    ) %>%
    arrange(Comparison, Tissue)
  
  write.csv(r2_summary,
            file.path(OUTPUT_DIR, "transcriptome_vs_proteome_R2_summary.csv"),
            row.names = FALSE)
  cat("Saved: transcriptome_vs_proteome_R2_summary.csv\n\n")
  cat("R2 Summary:\n")
  print(r2_summary, n = Inf)
}

# ==================== DONE ====================

cat("\n========================================\n")
cat("ALL DONE\n")
cat("========================================\n")
cat("Individual plots (15 PDFs):\n")
cat("  transcriptome_vs_{comparison}_{Tissue}.pdf\n\n")
cat("Combined facet plots (2 PDFs):\n")
cat("  transcriptome_vs_proteome_all_tissues.pdf\n")
cat("  transcriptome_vs_proteome_all_tissues_clean.pdf\n\n")
cat("Matched gene detail tables (15 CSVs):\n")
cat("  matched_genes_{Tissue}_{comparison}.csv\n")
cat("  Columns: GN, Protein_Accession, Description,\n")
cat("           mRNA_Log2FC, mRNA_pvalue, mRNA_sig,\n")
cat("           Log2FC_soluble/insoluble/ratio + p-values,\n")
cat("           sig_group\n\n")
cat("R2 summary table:\n")
cat("  transcriptome_vs_proteome_R2_summary.csv\n")
